### ISSUE TITLE
sometimes report 500 error

### ISSUE THREAD

**Issue by xiaoch05** [helix-bridge/helix-ui#41]
### Prerequisites

- [X] Are you running the latest version?

### Importance

General

### Priority

Low

### Reproduce steps

from transaction history list to transaction detail

### Actual behavior

<img width="340" alt="Screen Shot 2022-06-02 at 4 14 33 PM" src="https://user-images.githubusercontent.com/15799431/171585810-36bd92c2-22ab-4ca0-8551-d745417a2c33.png">

### Expected behavior

normal

**Comment by ZolaxZola** [comment]
Related issues arising from this.
1. When viewing a transaction detail page, I get an error whenever I refresh it
2. Have no way to share the transaction details page with someone else. Since they can only get 500 error when opening the URL
suggesting a higher priority,  as the above bad experiences are bound to happen and not infrequently.
